name: artifact workflow
on: workflow_dispatch
jobs: 
  context-artifact:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish01.outputs.script-file}}
    steps:
      - name: Get Code
        uses: actions/checkout@master
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: package project
        run: mvn clean package
      - name: publish jar filename
        id: publish01
        run: find target/*.jar -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: upload artificat
        uses: actions/upload-artifact@master
        with:
          name: dist-files
          path: |
            target
  deploy:
    needs: context-artifact
    runs-on: ubuntu-latest
    steps:
      - name: get build artifact
        uses: actions/download-artifact@master
        with:
          name: dist-files
      - name: output context
        run: dir
      - name: deploy
        run: echo "deploying"
    
      


