name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: amanp063/helloworld:0.0.1
      ports:
        - 8080
    steps:
      - name: container step
        run: echo "container running on port 8080"