name: test workflow
on: workflow_dispatch
jobs: 
  test-job:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@master
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with maven
        run: mvn -B package --file pom.xml


